version: '3.1'

services:
  db:
    image: mariadb:10.6
    restart: always
    container_name: database
    environment:
      MARIADB_ROOT_PASSWORD: Password123!
      MARIADB_DATABASE: inventory  # Primary database
      MARIADB_USER: app_user
      MARIADB_PASSWORD: app_password
      
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql  # Ensure init script is correctly mapped

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - "8080:8080"  # Access Adminer at http://localhost:8080
    environment:
      ADMINER_DEFAULT_SERVER: database  # Connect Adminer to the MariaDB service

volumes:
  db_data:
